### ISSUE TITLE
Easier passing data to rhs

### ISSUE THREAD

**Issue by maedoc** [Nicholaswogan/numblsoda#10]
Thanks for the package, some 400x faster than plain Python for the system I'm looking at.  I just wanted to point out that Numba functions close over their local scope so passing arbitrary (constant?) data can be much easier than in your example.  Mine looks like this:
```python
def make_lsoda_func(c,R,dstar,E,F,N):
    @cfunc(lsoda_sig)
    def rhs(t, x, du, p):
        codim3(t,x,c,R,dstar,E,F,N,du)
    return rhs
```

**Comment by Nicholaswogan** [comment]
This is a good way to do it! I'll update the Readme with this example. Only drawback is that changing any parameter requires recompiling the function right?

**Comment by maedoc** [comment]
Yes, that’s true. So it’s good for constants, but complex changing parameters still require your demo.
