### ISSUE TITLE
Cannot import dop853 from numbalsoda

### ISSUE THREAD

**Issue by samirop** [Nicholaswogan/numblsoda#16]
Hi! 
I've just installed your library and got this error when running the code shown in the readme.
`ImportError: cannot import name 'dop853' from 'numbalsoda'`
Could I be missing a library? Thanks in advance

**Comment by Nicholaswogan** [comment]
I have not gotten around to updating conda and pip with a version that has dop853.

If you install from source from the main branch, then dop853 will work.

To install from source you will need a fortran compiler and C++ compiler somewhere on your computer. From the root directly just run 'python setup.py install'

**Comment by samirop** [comment]
Thanks for your reply. Great job with this library
