### ISSUE TITLE
Make NumPy types for u0 and usol configurable

### ISSUE THREAD

**Issue by juhannc** [Nicholaswogan/numblsoda#17]
First of all, awesome code! I got a speedup of an order of magnitude basically for free!

But, as far as I can tell, `u0` and `usol` are required to be of type `np.float64`. However, often times `np.float32` is more than enough.

Maybe I just don't see the option to change it, but if it doesn't exist, it'd be nice if we could change it.

Thank you!

**Comment by Nicholaswogan** [comment]
Thanks! Ya, it should be possible to just compile the underlying C++ code for either float64 or float32. I will leave this open and get it to eventually.

**Comment by Nicholaswogan** [comment]
I am going to stick to float64 only.
