### ISSUE TITLE
Request for PyPI package

### ISSUE THREAD

**Issue by AgenttiX** [Nicholaswogan/numblsoda#2]
First of all, thanks for creating this great library! I'm developing a framework for [cosmological simulations](https://arxiv.org/abs/1909.10040), and NumbaLSODA speeds up our ODE integration by about 20x compared to using [scipy.integrate.odeint()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) with pure Python, and even more compared to [scipy.integrate.solve_ivp()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html).

Would it be possible for you to push NumbaLSODA wheels to PyPI? This would simplify our installation process, as the support for Git dependencies has been [dropped](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#dependencies-that-aren-t-in-pypi) from setuptools.

**Comment by Nicholaswogan** [comment]
@AgenttiX great to hear its useful! I will eventually upload to PyPi, but right now I'm a bit confused about how to do this properly when C++ extensions are involved.

**Comment by Nicholaswogan** [comment]
@AgenttiX Now uploaded to PyPI: https://pypi.org/project/NumbaLSODA/ . Should be pip installable, and you can add it as a dependency on other projects.
