### ISSUE TITLE
Adding other Runge-Kutta time integrators

### ISSUE THREAD

**Issue by ghost** [Nicholaswogan/numblsoda#23]
Hye again !

Could you please share the steps one would have to take to add a new Runge-Kutta integrator to the project ?

I'm happy to implement it push a PR at some point, but I wanted to know if you had maybe a process that would make it easier to add a new Butcher-tableau based RK integrator ?

Thanks !
T. Bridel-Bertomeu

**Comment by Nicholaswogan** [comment]
I don't have a streamlined abstracted system for adding a RK integrator. My approach so far has been 

1. Find an integrator that exist on Github/internet written in Fortran, C, or C++
2. Write some code in that language which has a c-interface, which is callable from Python ([see here](https://github.com/Nicholaswogan/numbalsoda/blob/main/src/wrapper.cpp))
3. Write some Python code which calls the functions from step 2 using c-types ([see here](https://github.com/Nicholaswogan/numbalsoda/blob/main/numbalsoda/driver.py))

So if you were to find an integrator more suitable to your application, you could follow this template to add it. a PR is welcome! thanks!

**Comment by ghost** [comment]
Thank you 👌 I'll will work on something and submit it for discussion.
