### ISSUE TITLE
Using numbalsoda solve_ivp

### ISSUE THREAD

**Issue by DanielLichtenecker** [Nicholaswogan/numblsoda#25]
Hi,

I would like to solve a stiff ODE with the solve_ivp wrapper by numbalsoda - as you did [here](https://github.com/Nicholaswogan/numbalsoda/blob/main/solve_ivp.ipynb). Unfortunatly i can't load the module solve_ivp from numbalsoda (not available in the package).

Could your provide the module solve_ivp?

**Comment by Nicholaswogan** [comment]
You are likely trying to run the notebook from the root directory of this repository. That will not work. Move the notebook to another directory then run it. There must not be a Lower directory which has the folder name “numbalsoda”. Make sure you have numbalsoda installed via conda.
