### ISSUE TITLE
What about people being stuck with windows at work 😓

### ISSUE THREAD

**Issue by edumur** [Nicholaswogan/numblsoda#3]
Hi,

Thanks for this package which make things so much faster!
Is there a way to make your pip install available to Windows user?
For instance by making a conda package from it?

**Comment by Nicholaswogan** [comment]
Ya it can work on Windows. One good solution is to upload Windows binaries (i.e. python wheels) to PyPi. I'll give it a try. But I have no experience with distributing binaries, so I might give up if I can't figure it out too quickly.

**Comment by Nicholaswogan** [comment]
Should work on Windows now when doing a pip install: `pip install NumbaLSODA`. So I'm closing this. Let me know if it doesn't work. 50e5887fa42cf9c6307c32f14f9f9eaaedb257c8
