### ISSUE TITLE
solve_ivp is missing or not added in conda package

### ISSUE THREAD

**Issue by ParvizRZ** [Nicholaswogan/numblsoda#30]
In installed numbalsoda using 'conda install' but importing solve_ivp failed. Comparing the content of the packages, installed via conda and pip, discovered that file **/driver_solve_ivp.py** is simply missing
_Traceback (most recent call last):
  File "<...>\test_numbalsoda.py", line 1, in <module>
    from numbalsoda import lsoda_sig, lsoda, dop853, solve_ivp
ImportError: cannot import name 'solve_ivp' from 'numbalsoda' (<...>\envs\conda_python310\lib\site-packages\numbalsoda\__init__.py)_

I encountered this issue while trying install the package via conda install to bypass the issue #29. 
Here is the folder with conda package:
![Capture2](https://github.com/Nicholaswogan/numbalsoda/assets/7829759/9b37a298-e0eb-4037-93d4-65ac50c72d8a)

**Comment by Nicholaswogan** [comment]
The problem is that the version with solve_ivp is not yet one conda.
