### ISSUE TITLE
Can't install with python 3.12

### ISSUE THREAD

**Issue by simonluzara** [Nicholaswogan/numblsoda#31]
Hello.
I would like to install the package, but I couldn't `pip install Numbalsoda` since it demands python version 3.9.

Is there a way to over ride this requirement? Cause I have got another package like SALib which needs a 3.11 or higher to use.

**Comment by Nicholaswogan** [comment]
You can install a version that works with Python 3.11 with `conda install -c conda-forge numbalsoda`
