### ISSUE TITLE
Numba cache and iterative solving

### ISSUE THREAD

**Issue by edumur** [Nicholaswogan/numblsoda#4]
Hi,

I am trying to use NumbaLSODA to solve many systems iteratively.
However, it seems that I can't out the function in the numba cache and so I have a big overhead at each iteration.
I was wondering if you have an advice about it.

This is my code.
First I put all numba related function inside a file

numba_func.py
```python
NOPYTHON = True
CACHE = True
PARALLEL = True

@nb.cfunc(lsoda_sig, nopython=NOPYTHON, cache=CACHE)
def rhs(x, i, di, p):
    di[0] = ...
    di[1] = ...
    di[2] = ...

funcptr = rhs.address

@nb.njit('(float64)(float64, float64, float64, int16)', nopython=NOPYTHON, parallel=PARALLEL, cache=CACHE)
def solve(a, b, c, funcptr):

    w0 = np.array([a, b, ...], dtype=np.float64)
    p  = np.array([c], dtype=np.float64)

    x = np.linspace(0, 100, 500)

    usol, success = lsoda(funcptr, w0, x, data=p)
    
    return usol[-1][1]

```

Then I use another file to solve the systems one after the others

```python

from numba_func import solve, funcptr

gs = []
for a, b, c in zip(as, bs, cs):
    gs = np.append(gs, solve(a, b, c, funcptr))
```

I got the following warning:
```bash
NumbaWarning: Cannot cache compiled function "solve" as it uses dynamic globals (such as ctypes pointers and large global arrays)
```

I guess the idea is to pass the variable `funcptr` correctly so that numba is happy but so far I failed...

**Comment by Nicholaswogan** [comment]
Ya the problem is probably with `funcptr`. I do not know how to deal with this, and I don't see a quick fix. But maybe stuartarchibald does. You can find him on the numba gitter page (https://gitter.im/numba/numba), or maybe you could open an issue on the numba github.

Let me know what you find.

**Comment by edumur** [comment]
Hi,

Well it was easy...
Simply write a one file
```python
NOPYTHON = True
CACHE = True
PARALLEL = True

@nb.cfunc(lsoda_sig, nopython=NOPYTHON, cache=CACHE)
def rhs(x, i, di, p):
    di[0] = ...
    di[1] = ...
    di[2] = ...

funcptr = rhs.address

@nb.njit('(float64)(float64, float64, float64)', nopython=NOPYTHON, parallel=PARALLEL, cache=False)
def solve(a, b, c):

    w0 = np.array([a, b, ...], dtype=np.float64)
    p  = np.array([c], dtype=np.float64)

    x = np.linspace(0, 100, 500)

    usol, success = lsoda(funcptr, w0, x, data=p)
    
    return usol[-1][1]
```

and the iteration became really fast.
I guess it makes sens when you know what you're doing

**Comment by Nicholaswogan** [comment]
But this doesn't answer how to cache a function like `solve`? Right?

**Comment by edumur** [comment]
True, it doesn't.
However, when I run this code, I do not see a measurable overhead.
In some sense, this is enough for me ^^' .
