### ISSUE TITLE
Potential interpolant issue

### ISSUE THREAD

**Issue by Patol75** [Nicholaswogan/numblsoda#5]
Hi @Nicholaswogan,

Great work on this repository, it looks like you managed a consistent and quite high speed-up compared to SciPy. I have been working with LSODA recently using `solve_ivp`, and I have encountered an issue relative to the interpolant [(PR at SciPy)](https://github.com/scipy/scipy/pull/14552). I am wondering if this implementation of LSODA also has a similar issue, as it looks to me that the root of the problem lies within the FORTRAN implementation. In particular, `LSODA::intdy` seems very similar to me to `DINTDY` in ODEPACK, which could well mean that the issue is present. Let me know if you can have a look.

**Comment by Nicholaswogan** [comment]
Thanks! This is interesting and seem hard to pin down and understand. I'll spend a bit of time on it. It might be worth opening an issue at LSODA.jl : https://github.com/rveltz/LSODA.jl , if the issue persists there. They might shed some light on the problem that would help this repository.

**Comment by Patol75** [comment]
I have had a look at LSODA.jl, and I can confirm there also looks to be an interpolant problem there - I will open an [issue](https://github.com/rveltz/LSODA.jl/issues/69).
