### ISSUE TITLE
Support for other integrators

### ISSUE THREAD

**Issue by ma-sadeghi** [Nicholaswogan/numblsoda#6]
Hi, thanks for this great package!

I know this package is only supposed to deal with the `lsoda` integrator, but I was wondering if you could at least add support for an explicit integrator as well, maybe `rk23`. The reason I ask is that I want to solve a very large system of ODEs (>10^6), and because of that, implicit integrators are not really suitable (since they require a matrix solve Ax=b at each step), so I'm stuck with scipy's `rk23` or `rk45`, which are fine, except that because the integration involves too many time steps, I think `solve_ivp`'s explicit `while` loop is becoming the bottle-neck.

**Comment by Nicholaswogan** [comment]
@ma-sadeghi Ya, I can add an explicit integrator. I think the best option might be DOPRI5 method: http://www.unige.ch/~hairer/software.html . There is a C++ implementation [here](https://github.com/bjodah/IntegratorT) which is wrap-able. I'll get around to it in the next week or so, unless you want to try.

**Comment by hunterqueb** [comment]
@Nicholaswogan +1 for implementing DOPRI5. I've been scouring for a good RK45 solver that has easy compatibility with numba nijt, and it's been a pain. I would love to see that implemented, especially since an RK45 solver is used so much in MATLAB.

**Comment by Nicholaswogan** [comment]
On closer inspection I don't think [this](https://github.com/bjodah/IntegratorT) implementation of DOPRI5 is the best. It wouldn't work right out of the box because the ODE function isn't passed, its kinda baked in. So still in search of a good implementation of DOPRI5 written in C or C++. The main requirement is that the RHS ODE function to passed to the integrator has to look something like

```C++
void ODE_Function(double t, double *u, double *du, void *data)
```

**Comment by Nicholaswogan** [comment]
I added this explicit RK integrator: https://github.com/jacobwilliams/dop853

5ad8cce583a2e1dfb721d7f4d6c9b135b718bd60

Appears to be speedier than lsoda for explicit problems.

Example:

```python
usol1, success = dop853(funcptr, u0, t_eval, data=data, rtol=1e-8, atol=1e-8,mxstep=1000)
```
